name: Memories in Transit
favicon: null
layout_spectrum: 1
typography_spectrum: 0.91485
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfd'
    - '#332e2b'
    - '#5c4b2d'
    - '#597e90'
    - '#8cb3b8'
  brandStrength: 0.25
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
